version: '3'
services: 
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports: 
      - 4160:4160
      - 4161:4161
    volumes:
      - nsq-io:/data/nsq-cv
    networks:
      - local-network
  nsqd:
    image: nsqio/nsq
    command: /nsqd --broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160
    ports: 
      - 4151:4151
      - 4150:4150
    volumes:
      - nsq-io:/data/nsq-pd
    networks:
      - local-network
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - 4172:4171
    networks:
      - local-network
  postgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_PASSWORD=root
    ports: 
      - 5432:5432
    networks:
      - local-network
    volumes:
      - postgres-pd:/data/postgres-db
  adminer:
    # admin dashboard for postgres
    image: adminer
    ports: 
      - 8081:8080
    networks:
      - local-network
  redis:
    image: 'redis:alpine'
    ports: 
      - 6379:6379
    networks:
      - local-network
    volumes:
      - redis-pd:/data/redis-db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    ports: 
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - local-network
    volumes:
      - elasticsearch-pd:/data/elasticsearch-db
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
volumes:
  elasticsearch-pd:
  redis-pd:
  postgres-pd:
  nsq-io: