version: '3'
services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    ports: 
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - local-network
    volumes:
      - elasticsearch-pd:/data/elasticsearch-db
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
volumes:
  elasticsearch-pd:
  redis-pd:
  postgres-pd:
  nsq-io: