version: '3'
services: 
  cassandra-1:
    image: cassandra:3.11
    ports: 
      - 9042:9042
    networks:
      - local-network
    volumes:
      - cassandra:/data/cassandra-1
    hostname: cassandra-1
  cassandra-2:
    image: cassandra:3.11
    command: /bin/bash -c "sleep 10 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    ports: 
      - 9043:9042
    environment:
      - CASSANDRA_SEEDS=cassandra-1
    networks:
      - local-network
    volumes:
      - cassandra:/data/cassandra-2
    hostname: cassandra-2
  cassandra-3:
    image: cassandra:3.11
    command: /bin/bash -c "sleep 60 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    ports: 
      - 9044:9042
    networks:
      - local-network
    environment:
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2
    volumes:
      - cassandra:/data/cassandra-3
    hostname: cassandra-3
  

networks:
  local-network:
    driver: bridge

volumes:
  cassandra: